const Galaxylist = [
  "Ambartsumian's Knot", 
"Andromeda galaxy",
"Andromeda",
"Antennae Galaxies",
"Aquarius Dwarf",
"Arp's Galaxy",
"Atoms-for-Peace",
"Baade's Galaxies",
"Barbon's Galaxy",
"Barnard's Galaxy",
"Bear's Paw" ,
"BL Lac"	,
"Black Eye Galaxy",
"Bode's Galaxies" ,
"Burbidge Chain" ,
"BW Tauri",
"Carafe galaxy",
"Carina dwarf",	
"Cartwheel galaxy",	
"Centaurus A" ,
"Circinus galaxy",	
"Coddington's Nebula",
"Copeland Septet" ,
"Cygnus A"	,
"Draco dwarf", 
"Fath 703" ,
"Fornax dwarf" ,				
"Fourcade-Figueroa object", 				
"The Garland", 				
"Grus Quartet" , 				
"GR8 DDO", 				
"Hardcastle Nebula ",			
"Helix Galaxy "	,			
"Hercules A ",				
"Holmberg I" ,				
"Holmberg II" ,				
"Holmberg III" ,				
"Holmberg IV" ,				
"Holmberg V ",				
"Holmberg VI", 				
"Holmberg VII", 				
"Holmberg VIII", 				
"Holmberg IX", 				
"Horologium Dwarf = Schuster's Spiral ",			
"Hydra A ",				
"Integral Sign Galaxy", 				
"Keenan's System",				
"Kowal's Object", 				
"Large Magellanic Cloud", 				
"Leo I = Harrington-Wilson No. 1",				
"Leo II = Harrington-Wilson No.2",		
"Leo A = Leo III ", 				
"Lindsay-Shapley Ring", 				
"McLeish's Object", 				
"Maffei I = UGCA 034", 				
"Maffei II = UGCA 039", 				
"Malin 1", 				
"Mayall's Object = Arp 148", 				
"Mice = NGC 4676 = Arp 242 ",				
"Minkowski's Object = Arp 133", 				
"Pegasus Dwarf = DDO 216", 				
"Perseus A = NGC 1275", 				
"Phoenix Dwarf Irregular", 				
"Pisces Cloud = NGC ", 				
"Pisces Dwarf = LGS 3", 				
"Reinmuth 80 = NGC 4517A", 				
"Reticulum Dwarf", 				
"Sagittarius Dwarf Irregular (SagDIG)", 				
"Sculptor Dwarf", 				
"Sculptor Dwarf Irregular", 				
"Seashell galaxy", 				
"Serpens Dwarf",				
"Sextans A = DDO 075", 				
"Sextans B = DDO 070", 				
"Sextans C", 				
"Seyfert's Sextet = NGC 6027/6027A-E", 				
"Shapley-Ames 1", 				
"Shapley-Ames 2",				
"Shapley-Ames 3", 				
"Shapley-Ames 4",				
"Shapley-Ames 5", 				
"Shapley-Ames 6 ",				
"Small Magellanic Cloud", 				
"Sombrero Galaxy",				
"Spindle Galaxy", 				
"Stephan's Quintet", 				
"Superantennae ",				
"Triangulum galaxy ",				
"Ursa Minor dwarf",		
"Whirlpool galaxy",
"Wild's Triplet" ,
"Wolf-Lundmark-Melotte", 
"Zwicky No.2" ,
"Zwicky's Triplet",
]